//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhel.Lunch.Requisition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public System.Guid Id { get; set; }
        public string Indentor { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> InternalTelephoneNumber { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<System.DateTime> DateOfLunch { get; set; }
        public string MenuType { get; set; }
        public Nullable<int> NumberOfGuest { get; set; }
        public Nullable<int> NumberOfHost { get; set; }
        public string GuestInfo { get; set; }
        public byte[] HODSignature { get; set; }
        public byte[] IndentorSignature { get; set; }
    
        public virtual RequisistionStatu RequisistionStatu { get; set; }
    }
}
